### PR TITLE
[WIP] 1D/categorical plots

### PR DESCRIPTION
**Pull request by brisvag**
An attempt at plotting categorical data as histograms, as requested in #4 . I'm not a huge fan of the current noodling that needs to happen for this to work, but I would like some feedback on the functionality.

Please, try out the example, @jni, and let me know!

EDIT: This PR now also addresses #2 and makes switching layers or altering layer data "seamless".

### CODE REVIEW

**Comment by jni** [comment]
@brisvag I'm getting a new error now with #2... 

<details>

<summary>

```pytb
ValueError: could not broadcast input array from shape (20,) into shape (13,)
```

</summary>

```pytb
 $ python pts-props-2d.py
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/projects/napari-properties-plotter/napari_properties_plotter/property_plotter.py in update(self=<napari_properties_plotter.property_plotter.PyQtGraphWrapper object>, idx=0, y=0     0.461403
1     0.291723
2     0.282881
3  ...  0.810063
12    0.679838
Name: b, dtype: float64, ystyle=<YStyle.scatter: 2>, color=(255, 225, 25), symbol='t1')
    184         symbol = symbol.value
    185         if ystyle is YStyle.scatter:
--> 186             plot = self.make_scatter(y, color, symbol)
        plot = undefined
        self.make_scatter = <bound method PyQtGraphWrapper.make_scatter of <napari_properties_plotter.property_plotter.PyQtGraphWrapper object at 0x16090d160>>
        y = 0     0.461403
1     0.291723
2     0.282881
3     0.577946
4     0.141412
5     0.920501
6     0.237381
7     0.651238
8     0.012964
9     0.516475
10    0.425593
11    0.810063
12    0.679838
Name: b, dtype: float64
        color = (255, 225, 25)
        symbol = 't1'
    187         elif ystyle is YStyle.line:
    188             plot = self.make_line(y, color)

~/projects/napari-properties-plotter/napari_properties_plotter/property_plotter.py in make_scatter(self=<napari_properties_plotter.property_plotter.PyQtGraphWrapper object>, y=0     0.461403
1     0.291723
2     0.282881
3  ...  0.810063
12    0.679838
Name: b, dtype: float64, color=(255, 225, 25), symbol='t1')
    195
    196     def make_scatter(self, y, color, symbol):
--> 197         return self.plotter.plot(self.x, y, name=y.name, symbol=symbol, symbolBrush=color, pen=None)
        self.plotter.plot = <bound method PlotItem.plot of <pyqtgraph.graphicsItems.PlotItem.PlotItem.PlotItem object at 0x16090daf0>>
        self.x = 0     0.376805
1     0.849123
2     0.944229
3     0.958980
4     0.290655
5     0.409624
6     0.842317
7     0.404817
8     0.508858
9     0.189360
10    0.473361
11    0.275945
12    0.682698
13    0.373322
14    0.657060
15    0.993958
16    0.730959
17    0.595644
18    0.162199
19    0.675459
Name: a, dtype: float64
        y = 0     0.461403
1     0.291723
2     0.282881
3     0.577946
4     0.141412
5     0.920501
6     0.237381
7     0.651238
8     0.012964
9     0.516475
10    0.425593
11    0.810063
12    0.679838
Name: b, dtype: float64
        global name = undefined
        y.name = 'b'
        symbol = 't1'
        global symbolBrush = undefined
        color = (255, 225, 25)
        global pen = undefined
    198
    199     def make_line(self, y, color):

~/conda/envs/alto/lib/python3.9/site-packages/pyqtgraph/graphicsItems/PlotItem/PlotItem.py in plot(self=<pyqtgraph.graphicsItems.PlotItem.PlotItem.PlotItem object>, *args=(0     0.376805
1     0.849123
2     0.944229
3  ...  0.162199
19    0.675459
Name: a, dtype: float64, 0     0.461403
1     0.291723
2     0.282881
3  ...  0.810063
12    0.679838
Name: b, dtype: float64), **kargs={'name': 'b', 'pen': None, 'symbol': 't1', 'symbolBrush': (255, 225, 25)})
    654             self.clear()
    655
--> 656         item = PlotDataItem(*args, **kargs)
        item = undefined
        global PlotDataItem = <class 'pyqtgraph.graphicsItems.PlotDataItem.PlotDataItem'>
        args = (0     0.376805
1     0.849123
2     0.944229
3     0.958980
4     0.290655
5     0.409624
6     0.842317
7     0.404817
8     0.508858
9     0.189360
10    0.473361
11    0.275945
12    0.682698
13    0.373322
14    0.657060
15    0.993958
16    0.730959
17    0.595644
18    0.162199
19    0.675459
Name: a, dtype: float64, 0     0.461403
1     0.291723
2     0.282881
3     0.577946
4     0.141412
5     0.920501
6     0.237381
7     0.651238
8     0.012964
9     0.516475
10    0.425593
11    0.810063
12    0.679838
Name: b, dtype: float64)
        kargs = {'name': 'b', 'symbol': 't1', 'symbolBrush': (255, 225, 25), 'pen': None}
    657
    658         if params is None:

~/conda/envs/alto/lib/python3.9/site-packages/pyqtgraph/graphicsItems/PlotDataItem.py in __init__(self=<pyqtgraph.graphicsItems.PlotDataItem.PlotDataItem object>, *args=(0     0.376805
1     0.849123
2     0.944229
3  ...  0.162199
19    0.675459
Name: a, dtype: float64, 0     0.461403
1     0.291723
2     0.282881
3  ...  0.810063
12    0.679838
Name: b, dtype: float64), **kargs={'name': 'b', 'pen': None, 'symbol': 't1', 'symbolBrush': (255, 225, 25)})
    209             'data': None,
    210         }
--> 211         self.setData(*args, **kargs)
        self.setData = <bound method PlotDataItem.setData of <pyqtgraph.graphicsItems.PlotDataItem.PlotDataItem object at 0x160959820>>
        args = (0     0.376805
1     0.849123
2     0.944229
3     0.958980
4     0.290655
5     0.409624
6     0.842317
7     0.404817
8     0.508858
9     0.189360
10    0.473361
11    0.275945
12    0.682698
13    0.373322
14    0.657060
15    0.993958
16    0.730959
17    0.595644
18    0.162199
19    0.675459
Name: a, dtype: float64, 0     0.461403
1     0.291723
2     0.282881
3     0.577946
4     0.141412
5     0.920501
6     0.237381
7     0.651238
8     0.012964
9     0.516475
10    0.425593
11    0.810063
12    0.679838
Name: b, dtype: float64)
        kargs = {'name': 'b', 'symbol': 't1', 'symbolBrush': (255, 225, 25), 'pen': None}
    212
    213     def implements(self, interface=None):

~/conda/envs/alto/lib/python3.9/site-packages/pyqtgraph/graphicsItems/PlotDataItem.py in setData(self=<pyqtgraph.graphicsItems.PlotDataItem.PlotDataItem object>, *args=(0     0.376805
1     0.849123
2     0.944229
3  ...  0.162199
19    0.675459
Name: a, dtype: float64, 0     0.461403
1     0.291723
2     0.282881
3  ...  0.810063
12    0.679838
Name: b, dtype: float64), **kargs={'name': 'b', 'pen': None, 'symbol': 't1', 'symbolBrush': (255, 225, 25)})
    575         profiler('set data')
    576
--> 577         self.updateItems( styleUpdate = self._styleWasChanged )
        self.updateItems = <bound method PlotDataItem.updateItems of <pyqtgraph.graphicsItems.PlotDataItem.PlotDataItem object at 0x160959820>>
        global styleUpdate = undefined
        self._styleWasChanged = True
    578         self._styleWasChanged = False # items have been updated
    579         profiler('update items')

~/conda/envs/alto/lib/python3.9/site-packages/pyqtgraph/graphicsItems/PlotDataItem.py in updateItems(self=<pyqtgraph.graphicsItems.PlotDataItem.PlotDataItem object>, styleUpdate=True)
    618             if self.opts.get('stepMode', False) in ("center", True):
    619                 x = 0.5 * (x[:-1] + x[1:])
--> 620             self.scatter.setData(x=x, y=y, **scatterArgs)
        self.scatter.setData = <bound method ScatterPlotItem.setData of <pyqtgraph.graphicsItems.ScatterPlotItem.ScatterPlotItem object at 0x161dbeca0>>
        x = <class 'numpy.ndarray'> (20,) float64
        y = <class 'numpy.ndarray'> (13,) float64
        scatterArgs = {'pen': (200, 200, 200), 'brush': (255, 225, 25), 'symbol': 't1', 'size': 10, 'data': None, 'pxMode': True, 'antialias': False}
    621             self.scatter.show()
    622         else: # ...hide if not.

~/conda/envs/alto/lib/python3.9/site-packages/pyqtgraph/graphicsItems/ScatterPlotItem.py in setData(self=<pyqtgraph.graphicsItems.ScatterPlotItem.ScatterPlotItem object>, *args=(), **kargs={'antialias': False, 'brush': (255, 225, 25), 'data': None, 'pen': (200, 200, 200), 'pxMode': True, 'size': 10, 'symbol': 't1', 'x': <class 'numpy.ndarray'> (20,) float64, 'y': <class 'numpy.ndarray'> (13,) float64})
    481         oldData = self.data  ## this causes cached pixmaps to be preserved while new data is registered.
    482         self.clear()  ## clear out all old data
--> 483         self.addPoints(*args, **kargs)
        self.addPoints = <bound method ScatterPlotItem.addPoints of <pyqtgraph.graphicsItems.ScatterPlotItem.ScatterPlotItem object at 0x161dbeca0>>
        args = ()
        kargs = {'x': <class 'numpy.ndarray'> (20,) float64, 'y': <class 'numpy.ndarray'> (13,) float64, 'pen': (200, 200, 200), 'brush': (255, 225, 25), 'symbol': 't1', 'size': 10, 'data': None, 'pxMode': True, 'antialias': False}
    484
    485     def addPoints(self, *args, **kargs):

~/conda/envs/alto/lib/python3.9/site-packages/pyqtgraph/graphicsItems/ScatterPlotItem.py in addPoints(self=<pyqtgraph.graphicsItems.ScatterPlotItem.ScatterPlotItem object>, *args=(), **kargs={'antialias': False, 'brush': (255, 225, 25), 'data': None, 'pen': (200, 200, 200), 'pxMode': True, 'size': 10, 'symbol': 't1', 'x': <class 'numpy.ndarray'> (20,) float64, 'y': <class 'numpy.ndarray'> (13,) float64})
    569                         raise Exception("Unknown spot parameter: %s" % k)
    570         elif 'y' in kargs:
--> 571             newData['x'] = kargs['x']
        newData = <class 'numpy.ndarray'> (13,) [('x', '<f8'), ('y', '<f8'), ('size', '<f8'), ('symbol', 'O'), ('pen', 'O'), ('brush', 'O'), ('visible', '?'), ('data', 'O'), ('hovered', '?'), ('item', 'O'), ('sourceRect', [('x', '<i8'), ('y', '<i8'), ('w', '<i8'), ('h', '<i8')]), ('sourceQRect', 'O'), ('targetQRect', 'O'), ('targetQRectValid', '?')]
        kargs = {'x': <class 'numpy.ndarray'> (20,) float64, 'y': <class 'numpy.ndarray'> (13,) float64, 'pen': (200, 200, 200), 'brush': (255, 225, 25), 'symbol': 't1', 'size': 10, 'data': None, 'pxMode': True, 'antialias': False}
    572             newData['y'] = kargs['y']
    573

ValueError: could not broadcast input array from shape (20,) into shape (13,)
```

</details>

where 13 is the number of not-deleted points after selecting + deleting...

**Comment by jni** [comment]
I also can't find a way to plot only a single feature histogram given the UI and this code...

**Comment by brisvag** [comment]
As usual, I merged changes and things went wrong :) I already solved that indexing problem, but it popped up again, it seems.

The single feature histogram currently works only with what is considered categorical (i.e: non-float and non-int). If your categorical property is of one of these types, then it's not doable yet; I have to add the ability to manually ask for it.

**Comment by jni** [comment]
> The single feature histogram currently works only with what is considered categorical (i.e: non-float and non-int). If your categorical property is of one of these types, then it's not doable yet; I have to add the ability to manually ask for it.

What is non-float and non-int? Are you using pandas categoricals? Also doing a histogram for floats is ~trivial? https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

**Comment by brisvag** [comment]
Fixed the indexing issue.

Yeah, doing the plot itself is trivial, it's fitting it within the rest of the functionality that's getting me stuck. The architecture of this plugin is not well thought out, and now I'm paying the price 😅

**Comment by brisvag** [comment]
@jni Check out the current state! If nothing is set on the `y` axis and the data is continuous, it will now plot a histogram based on a settable number of bins.

**Comment by jni** [comment]
@brisvag works for me! :tada: very awesome. Two notes:

- Numpy actually has automatic histogram bin selection algorithms, see the string argument description for bins in [this function](https://numpy.org/doc/stable/reference/generated/numpy.histogram_bin_edges.html#numpy.histogram_bin_edges). You can just do `np.histogram(values, bins='auto') to get a generally much nicer result than "10". 
- It would be nice to get area selection for histograms also! But that can come later.

**Comment by brisvag** [comment]
Sweet, auto binning looks great! Implemented both that and the selection during binning :)

**Pull request merged**
